adj = input("Adjective: ")
noun = input("Noun: ")
noun2 = input("Noun (end with period): ")
place = input("Place: ")
adj2 = input("Adjective (end with period): ")
noun3 = input("Noun (person): ")
noun4 = input("Weapon: ")
verb = input("Verb (past tense): ")
adj3 = input("Adjective: ")
print("""Once upon a time there was an extremely""", adj, noun, """who lived with his""", noun2, """The""", adj, noun,"""decided he would go on an adventure to""", place, """because he thought his""", noun3, """was extremely""", adj2, """He left his home to go to""", place,"""even though his""", noun3, """told him not too. When he arrived, he was met by his""", noun2, """He quickly pulled out his""", noun4, """and""", verb, """it. He then woke up and discovered it was all one""", adj3, """dream. Or was it?""" ) 