name = input("Name here: ")
age = input("Age here: ")
height = input("Height here (meters): ")
favnum = input("Favorite number here: ")
a = int(age)
f = int(favnum)
h = float(height)
print("Your name is:", name,"your age is", age, "your height is", height, "your favorite number is", favnum, "your new age is", a, "your new favorite number is",f, "and your new height is", h)